# Generated by Django 4.1.3 on 2022-11-15 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_traveller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='imag',
            field=models.ImageField(height_field=90, upload_to='pics', width_field=90),
        ),
    ]
