# Generated by Django 4.1.3 on 2022-11-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0003_alter_place_imag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='imag',
            field=models.ImageField(upload_to='pics'),
        ),
    ]
