# Generated by Django 4.1.3 on 2022-11-19 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_movie_imag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='imag',
            new_name='img',
        ),
    ]
